"""add order_items association table

Revision ID: 8a0a3bad4e52
Revises: a0be703bd6b0
Create Date: 2026-08-15 16:09:34.158851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0a3bad4e52'
down_revision = 'a0be703bd6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_order_items_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='chk_order_items_unit_price'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_order_items_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_order_items_product'),
    sa.PrimaryKeyConstraint('order_item_id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_items_order_product')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('idx_order_items_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_order_items_product_id', ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_order_items_product_id')
        batch_op.drop_index('idx_order_items_order_id')

    op.drop_table('order_items')
    # ### end Alembic commands ###
